### ISSUE TITLE
Upgrade SDK

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer#48]
Upgrade SDK and implement

- [x] New error type `ErrOrganizationNotFound` on the `retryUnlessNotFound` function
- [x] https://github.com/vocdoni/explorer/issues/27
- [x] Check the implementation of pagination https://github.com/vocdoni/interoperability/issues/188#issuecomment-2217720363
- [x] Related with previous point: https://github.com/vocdoni/explorer/issues/13
- [x] New SET_PROCESS transaction types (related: https://github.com/vocdoni/explorer/issues/19)
- [x] Implement txCount for block https://github.com/vocdoni/explorer/issues/63
